### ISSUE TITLE
Overlay not found 

### ISSUE THREAD

**Issue by AllanElleuch** [IlikePepsi/dt-overlays#1]
Hi I tried a make i2c1_install but I got somes errors on the way : 

`root@beaglebone:/home/debian/git/dt-overlays# make i2c1_install
make[1]: Entering directory '/home/debian/git/dt-overlays/i2c1'

Building..
    ..overlay..
dtc -O dtb -o i2c1-00A0.dtbo -b 0 -@ i2c1.dts

Installing i2c1..
    ..install overlay binary..
    ..install udev rules..
/bin/sh: 1: [[: not found
    ..set boot parameter..
    ..assign overlay slot..
    ..install i2c1 bus devices..
make[2]: Entering directory '/home/debian/git/dt-overlays/i2c1/rtc@68'
    ..rtc@68..
    ..install systemd unit..
    ..install clock-updater script..
    ..install udev rule..
Overlay not found.
Traceback (most recent call last):
  File "../scripts/set_uenv.py", line 161, in <module>
    main()
  File "../scripts/set_uenv.py", line 86, in main
    words = split_line(line)
  File "../scripts/set_uenv.py", line 69, in split_line
    return [tmp[0].strip()] + [w.strip('= ') for w in tmp[1].split()]
IndexError: list index out of range
Failed to enable unit: Unit file /lib/systemd/system/hwclock.service is masked.
Makefile:13: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/debian/git/dt-overlays/i2c1/rtc@68'
Makefile:32: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/debian/git/dt-overlays/i2c1'
Makefile:2: recipe for target 'i2c1_install' failed
make: *** [i2c1_install] Error 2
`

I am pretty interested to solve this, if you have a solutio

**Comment by SuFizz** [comment]
Dont use the make scripts. Instead just use dtc and create it yourself and copy it back to your /lib/firmware
https://stackoverflow.com/questions/33549211/how-to-add-i2c-devices-on-the-beaglebone-black-using-device-tree-overlays
